### ISSUE TITLE
Change license to GPLv3+

### ISSUE THREAD

**Issue by vanitasvitae** [vanitasvitae/EnigmAndroid#15]
@afmachado since you contributed to the app by translating it to brazil, I'd like to ask, whether you would mind if I change the apps license from GPLv2-only to GPLv3+.

I think this would benefit the user, as well as developers since it would become easier to combine the software with other licenses such as Apache License v2 (see [here](http://www.ifross.org/en/what-difference-between-gplv2-and-gplv3)).

**Comment by afmachado** [comment]
I fully agree

**Comment by vanitasvitae** [comment]
Done in a31a653b2ea33f3f84ad3338e7f0e646bc325f4e
