### ISSUE TITLE
Description on fdroid

### ISSUE THREAD

**Issue by FsShigeki** [vanitasvitae/EnigmAndroid#3]
Hi, you are wrong, Polish mathematics broke enigma, read wikipedia and edit your description please. Thanks

**Comment by vanitasvitae** [comment]
Hi! I think the english article about the enigma is not the best source. I used to rely on the way longer german atricle. It's true that polish cryptographers worked on breaking the enigma and they had success, but the enigma was "truely" broken ("usable broken") by Alan Turing. Of course he used the work of Marian Rejewski, Jerzy Różycki and Henryk Zygalski. 

I will update the description nevertheless, this was only a quick and dirty summary ;)

Sources: https://de.wikipedia.org/wiki/Enigma_%28Maschine%29#Entzifferung
https://en.wikipedia.org/wiki/Alan_Turing

**Comment by vanitasvitae** [comment]
@fsShigeki I updated the description :)

**Comment by FsShigeki** [comment]
Best source http://theinstitute.ieee.org/technology-focus/technology-history/ieee-milestone-honors-polands-world-war-ii-code-breakers

Thanks for update ;)

**Comment by vanitasvitae** [comment]
You're welcome ;)
