### ISSUE TITLE
Alan Turing in the description on f-droid page

### ISSUE THREAD

**Issue by etam** [vanitasvitae/EnigmAndroid#5]
Steps to reproduce: Open the page https://f-droid.org/repository/browse/?fdid=de.vanitasvitae.enigmandroid
The problem: There is a sentence: "It has been broken by the great british mathematician Alan Turing."
The solution: Please have a look at the second paragraph of the page https://en.wikipedia.org/wiki/Enigma_machine

**Comment by vanitasvitae** [comment]
The "problem" is already known and fixed. The fixed description will be inculded in the next release.
Edit: Added the file to the repo. See https://github.com/vanitasvitae/EnigmAndroid/blob/master/de.vanitasvitae.enigmAndroid.txt

Vanitas

**Comment by etam** [comment]
Thanks. Sorry I didn't check closed issues.

**Comment by vanitasvitae** [comment]
No Problem ;)
