### ISSUE TITLE
Add other Enigma models into the app

### ISSUE THREAD

**Issue by DonaldTsang** [vanitasvitae/EnigmAndroid#6]
Thank you.

**Comment by vanitasvitae** [comment]
Hi!
Thats a nice idea! I will see, if I can find enough information about the different specifications of the enigma models to implement this :)

**Comment by vanitasvitae** [comment]
Wow, thats hard work, I have to rewrite major parts of the code again. But im on it :)

**Comment by vanitasvitae** [comment]
I added Enigma I, M3 and M4 so far. More to come soon :)
