### ISSUE TITLE
Mix and Match rotors and reflectors from different Enigma models

### ISSUE THREAD

**Issue by DonaldTsang** [vanitasvitae/EnigmAndroid#7]
See GCC geocache tool as a comparison.

**Comment by DonaldTsang** [comment]
Geocache Calculator I meant to say

**Comment by vanitasvitae** [comment]
I think I will add kinda universal machine, but since I dont think this would be THAT useful, this wont be implemented in near future. I'll have to implement all Enigma models first.

**Comment by DonaldTsang** [comment]
And also allowing to add as much rotor wheels as you wish (max is 7 for Geocache Calculator).

**Comment by vanitasvitae** [comment]
That wont be so easy due to the way I implemented the stuff for now. I will nevertheless try it :)

**Comment by DonaldTsang** [comment]
Okay thanks.

**Comment by DonaldTsang** [comment]
www.cryptomuseum.com/crypto/enigma/g/a28.htm
www.cryptomuseum.com/crypto/enigma/uhr/index.htm
www.cryptomuseum.com/crypto/enigma/ukwd/index.htm
www.cryptomuseum.com/crypto/enigma/lf/index.htm

These would be a challenge... For the future...

**Comment by vanitasvitae** [comment]
Afaict, the a28 is the same as the g31, but smaller.
The UKWD is already implemented. You can use it with Enigma model D.
The Uhr and Lückenfüllerwalze are pretty interresting though. 
Thanks for the links :)

**Comment by DonaldTsang** [comment]
Found a way to generate rotor anti-tables for any custom rotors.
For an array input, make the output array Out[n] = the position of the number n in In[n]

**Comment by vanitasvitae** [comment]
Yes I wrote a little script that does the same. Very comfortable. I can enter rotors like "MTNCZ..." and it prints "new Integer[]{table}, new Integer[]{anti-table}". May I include it into the repo?

**Comment by DonaldTsang** [comment]
If you add an option to import or create+save your own rotors with custom "rotor clicks" and reflectors, then that will be awesome! 
Also, if you are going to allow custom n-rotor machine, only allow beta and gamma to be the last rotor.

**Comment by DonaldTsang** [comment]
E.g. You can select an N-rotor machine, and Beta and Gamma (or the lack of it) are only in rotor (N+1), while all other rotor models can be put anywhere. Also, Entry rotors (or the lack of it) should be allowed to mix and match as well.

**Comment by DonaldTsang** [comment]
Extra note:
The number of ways you can plug in 10, 11 and 12 cables are in the ratio of 22:30:15

**Comment by vanitasvitae** [comment]
Thats a nice idea. I will see, what I can do, but I am busy right now because I have to learn for exams :/
However, pull requests are welcome ;)

**Comment by DonaldTsang** [comment]
Could you also write a piece of psuedocode explaining how the algorithm works, so i can rewrite it in my own programming language?

**Comment by vanitasvitae** [comment]
I will see, if I find time for that anytime soon. Right now I'm still busy :/
If you know how to code Java, you can take a look at the package enigma. In there are most "core parts" which mimic the mechanical parts. Otherwise take a look on the wikipedia article :)

**Comment by vanitasvitae** [comment]
@DonaldTsang I just wrote a small wiki page about how the enigma works. I hope that helps you a little programming it in your own language.

**Comment by vanitasvitae** [comment]
won't fix
