### ISSUE TITLE
Use different colors for a pair of letters in the Steckbrett-verbindungen

### ISSUE THREAD

**Issue by JensKorte** [vanitasvitae/EnigmAndroid#8]
Then it is easier to see the connections.

**Comment by vanitasvitae** [comment]
That's a good idea. I already thought about it, but forgot it again :)
Will try to implement it in the next release.

**Comment by vanitasvitae** [comment]
Fixed #8, I added some colors to the dialog. But I have some other things on my todo list, so it will take some time till the next release on FDroid. You may of course build the app on your own :)
